# code: language=ansible

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install common apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages.debian.apps }}"
    state: present

- name: Install LinuxBrew
  ansible.builtin.import_tasks: apps/linux/brew.yml
- name: Install Oh My Zsh
  ansible.builtin.import_tasks: apps/oh-my-zsh.yml
- name: Install Chezmoi
  ansible.builtin.import_tasks: apps/chezmoi.yml
