- name: Gather facts about the system
  become: true
  ansible.builtin.setup:
    gather_subset:
      - "!user"

- name: Gather facts about the user
  ansible.builtin.setup:
    gather_subset:
      - "user"

- name: Install common packages in Debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install common packages in macOS
  ansible.builtin.import_tasks: macos.yml
  when: ansible_os_family == "Darwin"
